### ISSUE TITLE
Execution failed for task ':processResources'.

### ISSUE THREAD

**Issue by HoseonYim** [dacoev/SMFOS#2]
Execution failed for task ':processResources'.
> Entry plugin.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0/dsl/org.gradle.api.file.CopySpec.html#org.gradle.api.file.CopySpec:duplicatesStrategy for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by dacoev** [comment]
Can't build the pre-release because of this bug gonna fix this soon

**Comment by HoseonYim** [comment]
It looks it is getting the error because of the setting of Minecraft Development plugin in IntelliJ.  
It's setting use gradle5, but I use gradle7.  
Gonna make the project by myself or etc.

**Comment by HoseonYim** [comment]
maybe make the project with kotlin..?
